# Generated by Django 5.2.2 on 2025-06-08 16:11

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0004_remove_profile_profile_picture_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='../default_profile_qtk8ec', max_length=255, null=True, verbose_name='image'),
        ),
    ]
