# Generated by Django 5.2.2 on 2025-06-08 16:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0005_remove_profile_image_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_profile_qtk8ec', max_length=255, null=True, verbose_name='image'),
        ),
    ]
